# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-11-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to=functools.partial(posts.models._update_filename, *(), **{'path': 'images/'}))),
            ],
        ),
    ]
